Udpate and rename bat files
MiraGeoscience/peak-finder-app pull request #65
Opened 2024-05-16 18:48 UTC by domfournier

2024-05-16 19:48 UTC, sebhmg commented on install_for_analyst.bat
> +"%MIRA_CMD_RUNNER_DIR%\MambaEnvRunner.exe" --install "%curdir%\environments\conda-py-3.10-win-64.lock.yml" --with-pip-deps %* --run pip install -e .[dash] %*
I had hacked a quick thing  to install petro-lingo all from pip under a new env for Analyst,
but that does not quite apply here.

Command is more:
```suggestion
"%MIRA_CMD_RUNNER_DIR%\MambaEnvRunner.exe" --name peak-finder --install "%curdir%environments\py-3.10-win-64.conda.lock.yml" ^
  --run "pip install -e .[dash]" %*
```

2024-05-16 19:55 UTC, sebhmg requested changes
`install_in_mirageo,bat` is not quite correct

2024-05-16 19:55 UTC, sebhmg commented on install_for_analyst.bat
> +"%MIRA_CMD_RUNNER_DIR%\MambaEnvRunner.exe" --install "%curdir%\environments\conda-py-3.10-win-64.lock.yml" --with-pip-deps %* --run pip install -e .[dash] %*
update app in the first line comment:
```bat
:: Creates an environment for peak-finder-app under the Python environment location used by Geoscience Analyst.
```

2024-05-16 21:00 UTC, sebhmg approved these changes

2024-05-16 21:22 UTC, sebhmg requested changes
my recommendation would be to make installation non-editable for end users. Possibly have a helper script to turn it into editable installation for developers.

(Ideally, installation should not require users to download the repo. Will address that when reworking on the management of conda and pip dependencies)

2024-05-16 21:22 UTC, sebhmg commented on install.bat
>    && call "!MY_CONDA!" run -n %ENV_NAME% pip install -e .[dash]
for users, I would not make it editable
```suggestion
  && call "!MY_CONDA!" run -n %ENV_NAME% pip install .[dash]
```

As for developers, we could have a helper script `make-editable.bat` to patch the installation and point to the local source.

2024-05-16 21:23 UTC, sebhmg commented
@domfournier , I will PR on the this PR branch with a suggestion of scripts (non-editable, patch as editable)

2024-05-22 17:46 UTC, benk-mira approved these changes

2024-05-22 22:44 UTC, sebhmg approved these changes

2024-05-22 22:45 UTC, merged